[workspace]
members = [
    "qemu",
]
resolver = "2"

[package]
name = "interrupts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
harness = false

[[bin]]
name = "interrupts"
test = false