[package]
name = "interrupts"
version = "0.1.0"
edition = "2021"

[dependencies]
sbi-rt = "0.0.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bin]]
# name = "kernel"
# test = false
# bench = false