[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = "-C target-feature=-c"     # Disable compressed instructions
runner = "cargo run --package qemu --"

[target.x86_64-unknown-linux-gnu]
